### ISSUE TITLE
Add README.md referencing the original author as exercise about information

### ISSUE THREAD

**Issue by rien** [dodona-edu/programmeursleerling#307]

**Comment by pdawyndt** [comment]
@rien ready for review. I have added about pages to all learning activities in the course:

- English: `readme.md`, `about.en.md` (the latter will be removed as soon as the former is supported)
- Dutch: `about.nl.md`

All learning activities have a copied version of the readme.  If needed, I could also write a script that inserts the section/exercise numbers from the original book to the about pages of the individual learning activities.

**Comment by rien** [comment]
Looks fine to me :)
